defaults:
  years: 2000-2016
  date: latest
  citation-registers:
    - Scopus
    - WoS
    - GS
  process-journals: false
  journal-catalog-file: journal-catalog.csv
  output-dir: out
  publications-data-file-suffix: publications.csv
  citations-data-file-suffix: citations.csv
  journals-data-file-suffix: journals.csv


# All
all:
  process-journals: true

# P. Celec
celec:
