defaults:
  output-dir: out

all-publications-data:
  class: PublicationsData
  source:
    Scopus: all-scopus-{date}.csv
    WoS: all-wos-{date}.csv
  years: 2000-2016
  select: [ Year, Scopus, WoS ]

all-citations-data:
  class: CitationsData
  source:
    Scopus: all-scopus-{date}.csv
    WoS: all-wos-{date}.csv
  years: 2000-2016
  select: [ Year, Scopus, WoS ]

journals-data:
  class: JournalsData
  source: all-merged-{date}.csv
  journal-catalog: journal-catalog-{date}.csv
  select: [ Source title, Papers, ISI JIF, SJR, Scimago h-index, CiteScore, SNIP, Notes ]

results-data:
  class: ResultsData
  source: results-all-{date}.csv
  extract: [ Papers, Citations, Papers_Author, Cites_Paper ]
  groups: [ KB, KBt, KCh, KER, KAIM ]
  select: [ Group, Scopus, WoS, GS ]
